os: linux
dist: bionic
language: cpp

services:
  - docker

script:
  # Compile from source
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run divi
after_failure:
  - cat ./src/test-suite.log