os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - sudo apt-get install jq -y
  - sudo cat /etc/docker/daemon.json | jq '. + { "ipv6":true }' | sudo tee /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
script:
  # Compile from source
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run --name test_container --detach -t divi
  - docker exec -it test_container sh -c "make check"
  - docker exec -it test_container sh -c "cd qa/rpc-tests/ && ./test_runner.py && cd ../../"
after_failure:
  - docker cp test_container:/app/src/test-suite.log .
  - cat test-suite.log