os: linux
dist: trusty
sudo: false
language: cpp

services:
  - docker

before_install:
  - apt-get install jq -y
  - cat /etc/docker/daemon.json | jq '. + { "ipv6":true }' | sudo tee /etc/docker/daemon.json
  - cat /etc/docker/daemon.json
script:
  # Compile from source
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run --name test_container --detach -t divi
  - docker exec -it test_container bash "make check"
  - docker exec -it test_container bash "pushd qa/rpc-tests/ && ./test_runner.py && wait && popd"
after_failure:
  - docker cp test_container:/app/src/test-suite.log .
  - cat test-suite.log