os: linux
dist: bionic
language: cpp

services:
  - docker

script:
  # Compile from source
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run -t -d --name test_container divi
  - docker container ls -a
  - container_id=$(docker ps -aqf "name=test_container")
  - echo "${container_id}"
  - docker exec -it ${container_id} sh -c 'make check && pushd qa/rpc-tests/ && ./test_runner.py && popd && exit'

after_failure:
  - cat ./src/test-suite.log