os: linux
dist: bionic
language: cpp

services:
  - docker

script:
  # Compile from source
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run divi
  - docker exec -it divi sh -c 'make check'
  - docker exec -it divi sh -c 'pushd qa/rpc-tests/ && ./test_runner.py && popd'
after_failure:
  - cat ./src/test-suite.log